# Setup Plex Container
- name: plex container
  docker_container:
    name: "plex"
    image: "plexinc/pms-docker"
    state: "started"
    restart_policy: "always" 
    volumes:
    - "{{ host_plex_config_path }}:/config"
    - "{{ host_media_tv_path }}:/data/tvshows"
    - "{{ host_media_movies_path }}:/data/movies"
    - "{{ host_media_anime_path }}:/data/anime"
    - "{{ plex_transcode_path }}:/transcode"
    ports:
    - '32400:32400'
    - '3005:3005'
    - '8324:8324'
    - '32469:32469'
    - '1900:1900' 
    - '32410:32410' 
    - '32412:32412' 
    - '32413:32413' 
    - '32414:32414' 
    log_driver: 'syslog'
    log_opt:
      tag: "plex"
    env:
      TZ: "{{ TZ_TimeZone }}"
      PLEX_CLAIM: '{{ plex_claim }}' 
      ADVERTISE_IP: '{{ advertise_ip }}'
      ALLOWED_NETWORKS: '{{ allowed_networks }}'
      HOSTNAME: '{{ plex_hostname }}'
